version: "3.6"

services:
  # --- Kafka & Zookeeper ---
  zookeeper:
    image: 'confluentinc/cp-zookeeper:7.7.0'
    hostname: zookeeper
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - '2181:2181'
    volumes:
      - ./zookeeper_data:/var/lib/zookeeper/data
      - ./zookeeper_log:/var/lib/zookeeper/log
    restart: always

  kafka:
    image: 'confluentinc/cp-kafka:7.7.0'
    hostname: kafka
    container_name: kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:19092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:19092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - '9092:9092'
      - '19092:19092'
    volumes:
        - ./kafka_data:/var/lib/kafka/data
    restart: always

  kafka-ui:
    image: 'provectuslabs/kafka-ui:v0.7.2'
    container_name: kafka-ui
    ports:
      - '8888:8080'
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
    depends_on:
      - kafka
    restart: always

  minio:
    image: minio/minio:RELEASE.2024-07-04T14-25-45Z
    container_name: minio
    restart: always
    volumes:
      - ./s3_data:/data
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"

  ch_server:
    image: clickhouse/clickhouse-server:25.12
    container_name: click_house
    ports:
      - "8123:8123"
    environment:
      CLICKHOUSE_USER: click
      CLICKHOUSE_PASSWORD: click
    volumes:
      - ./clickhouse_data:/var/lib/clickhouse
    restart: always

  python-app:
    build: .
    container_name: python_app
    depends_on:
      - kafka
      - minio
      - ch_server
    restart: always